import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import "./updata.css";
import Upadatanav from "./Updatanav";
import { Suspense } from "react";
import { h1 } from "framer-motion/client";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Friends Telecom",
  description: "Generated by create next app",
};

export default function DeshboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div
      className={`${geistSans.variable} ${geistMono.variable} antialiased`}
    >
     <section >
     <Upadatanav />
      <Suspense fallback={<h1>loading...</h1>}>
      {children}


      </Suspense>

     </section>
      
    </div>
  );
}
