import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./checkout.css";
import { Suspense } from "react";
import ResponsiveEcommerce from "../../components/components/ResponsiveEcomerce";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Friends Telecom",
  description: "Generated by create next app",
  icons : {
    icon : "/favicon.jpg"
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
<Suspense fallback={<div>Loading...</div>}>
<ResponsiveEcommerce></ResponsiveEcommerce>


              {children}
              </Suspense>



          

      
       
      </body>
    </html>
  );
}
