import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ResponsiveEcommerce from "../components/ResponsiveEcomerce";
import NextAuthjsProvider from "@/providers/NextAuthjsProvider";
import { Suspense } from "react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  
  title: "Friends Telecom",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      
      <meta name="facebook-domain-verification" content="agpej8ithgyhkzuoqrzjmlgt9ksype" />
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Suspense fallback={<div>Loading...</div>}>
        <NextAuthjsProvider>
            <ResponsiveEcommerce></ResponsiveEcommerce>

            {children}

        </NextAuthjsProvider>
            </Suspense>

      
       
      </body>
    </html>
  );
}
